classy_clash: libraylib.a main.cpp
	clang -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -std=c++11 libraylib.a main.cpp -o classy_clash

clean:
	rm *.o classy_clash
